name: WonderBow
main: org.kitteh.tenjava.jul2014.WonderBow
version: '${project.version}'
description: The bow that does it all!
commands:
  wonderbow:
    description: Wonderbow debug commands
    usage: For options, type /wonderbow
permissions:
  wonderbow.command.craft:
    default: op
    description: Ability to craft a WonderBow from command